version: '3'

tasks:
  macos_install_deps:
    cmds:
      - brew install conftest kubeconform kube-score
  update_version:
    cmds:
      - grep version charts/replicated-library/Chart.yaml | cut -d' ' -f2 > ./library_chart_version
      - cp test-charts/test-replicated-library/Chart.yaml.tmpl test-charts/test-replicated-library/Chart.yaml
      - 'sed -i.bak "s/^  version:.*$/  version: $(cat ./library_chart_version)/" test-charts/test-replicated-library/Chart.yaml'
      - rm -f test-charts/test-replicated-library/Chart.yaml.bak
      - rm -f ./library_chart_version
  test:
    cmds:
      # Make sure we have a clean slate (for local use)
      - rm -rf charts
      # Update the chart dependencies
      - helm dependency update
      # Render the Helm chart
      - helm template -f tests/{{.VALUES}}.yaml testrelease . > rendered.yml
      # Run kubeconform
      # TODOLATER: -kubernetes-version
      # TODO: -strict
      - kubeconform -schema-location default -summary rendered.yml
      # Run kube-score
      # TODO: get more of these to pass then enable...
      # - kube-score score --ignore-container-cpu-limit --ignore-container-memory-limit --ignore-test pod-networkpolicy --ignore-test container-image-pull-policy --ignore-test container-ephemeral-storage-request-and-limit rendered.yml
      # Run conftest feeding in the values-specific .rego file
      # TODO: fiddle with this locally before enabling, need to get some sane policies in place first...
      # - conftest test rendered.yml
    deps: [update_version]
    dir: test-charts/{{.CHART}}
    vars:
      CHART: test-replicated-library
    # TODOLATER: refactor once https://github.com/go-task/task/pull/1204 is merged/released?
    preconditions:
      - sh: "[ {{.CHART}} ]"
        msg: "CHART env var not set, should be the name of a directory in test-charts"
      - sh: "[ {{.VALUES}} ]"
        msg: "VALUES env var not set, should be the name of a YAML file in test-charts/CHART/tests/ (without the .yaml suffix)"
