version: '3'

tasks:
  update_version:
    cmds:
      - grep version charts/replicated-library/Chart.yaml | cut -d' ' -f2 > ./library_chart_version
      - 'sed -i .bak "s/^  version:.*$/  version: $(cat ./library_chart_version)/" test-charts/test-replicated-library/Chart.yaml'
      - rm -f test-charts/test-replicated-library/Chart.yaml.bak
      - rm -f ./library_chart_version
  test:
    cmds:
      # Make sure we have a clean slate (for local use)
      - rm -rf charts
      # Update the chart dependencies
      - helm dependency update
      # Render the Helm chart
      - helm template -f tests/{{.VALUES}} testrelease .
      # Run kubeconform
      # Run kube-score
    deps: [update_version]
    dir: test-charts/{{.CHART}}
    vars:
      CHART: test-replicated-library
    # TODOLATER: refactor once https://github.com/go-task/task/pull/1204 is merged/released?
    preconditions:
      - sh: "[ {{.CHART}} ]"
        msg: "CHART env var not set, should be the name of a directory in test-charts"
      - sh: "[ {{.VALUES}} ]"
        msg: "VALUES env var not set, should be the name of a YAML file in test-charts/CHART/tests/"
