# values.yaml
# For values.yaml configuration options and examples, refer to the values-example.yaml file.

global:
  # -- Set additional global labels.
  labels: {}
  # -- Set additional global annotations.
  annotations: {}
  # -- Set the full object prefix, defaults to releasName-ChartName if not set. This value takes precedence over nameOverride.
  fullNameOverride:
  # -- Set an override for the ChartName, defaults to ChartName if not set.
  nameOverride:

defaults:
  image:
    pullPolicy: IfNotPresent
  strategy: RollingUpdate
  probes:
    livenessProbe:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
      terminationGracePeriodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 5
    startupProbe: {}

supportBundle:
  enabled: true
  installDefaultSpec: true
