{{- if .Values.test -}}

{{- /* Create global context dicts */ -}}
{{- $_ := set $ "ContextNames" dict -}}
{{- $_ := set $ "ContextValues" dict -}}


{{ include "replicated-library.serviceAccounts" . | nindent 0 }}

{{- end -}}
