{{- if .Values.test -}}

{{- /* Create global context dicts */ -}}
{{- $_ := set $ "ContextNames" dict -}}
{{- $_ := set $ "ContextValues" dict -}}

{{- range $name, $serviceAccountValues := .Values.serviceAccounts -}}
  {{- $_ := set $.ContextNames "serviceAccount" $name -}}
  {{- $_ := set $.ContextValues "serviceAccount" $serviceAccountValues -}}

  {{- include "replicated-library.serviceAccount" $ | nindent 0 }}
  {{- $_ := unset $.ContextNames "serviceAccount" -}}
  {{- $_ := unset $.ContextValues "serviceAccount" -}}
{{- end -}}
{{- end -}}
